version: '3.8'

services:
  # Reverse proxy Nginx
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - royella-network
    depends_on:
      - royella-app

  # Application Royella (Frontend)
  royella-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: royella-app
    restart: unless-stopped
    expose:
      - "80" # Expose seulement dans le réseau interne
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - nginx_logs:/var/log/nginx
    networks:
      - royella-network

volumes:
  nginx_logs:
    driver: local

networks:
  royella-network:
    driver: bridge 