services:
  # Reverse proxy Nginx for production
  nginx-proxy-prod:
    image: nginx:alpine
    container_name: nginx-proxy-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx-prod:/var/log/nginx
      - ./docker/ssl:/etc/nginx/ssl  # SSL certificates volume
    networks:
      - royella-prod-network
    depends_on:
      - royella-app-prod

  # Application Royella (Frontend) - Production
  royella-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: royella-app-prod
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - nginx_logs_prod:/var/log/nginx
    networks:
      - royella-prod-network

volumes:
  nginx_logs_prod:
    driver: local

networks:
  royella-prod-network:
    driver: bridge 